# Generated by Django 5.0.2 on 2025-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentalitem_owner_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='How many of this item are available?'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
